export const Users = [
    {
        id: 1,
        profilePicture: "Assets/person/2.jpeg",
        username: "Mahfid Antor",
    },
    {
        id: 2,
        profilePicture: "Assets/person/2.jpeg",
        username: "ZR Joy",
    },
    {
        id: 3,
        profilePicture: "Assets/person/3.jpeg",
        username: "Sanzida promi",
    },
    {
        id: 4,
        profilePicture: "Assets/person/4.jpeg",
        username: "Mohasina Bizly",
    },
    {
        id: 5,
        profilePicture: "Assets/person/5.jpeg",
        username: "Sanjida Akter",
    },
    {
        id: 6,
        profilePicture: "Assets/person/6.jpeg",
        username: "Bushra Akter",
    },
    {
        id: 7,
        profilePicture: "Assets/person/7.jpeg",
        username: "Zannat Tamim",
    },
    {
        id: 8,
        profilePicture: "Assets/person/8.jpeg",
        username: "Mirza Nitu",
    },
    {
        id: 9,
        profilePicture: "Assets/person/9.jpeg",
        username: "Zannatul Ferdous Zinnia",
    },
    {
        id: 10,
        profilePicture: "Assets/person/2.jpeg",
        username: "Rakib Ibn Ahsan",
    },
];
export const Posts = [
    {
        id: 1,
        desc: "Love for all,hatred for none",
        photo: "Assets/post/1.jpeg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        desc: "Live,Love,Laugh",
        photo: "Assets/post/2.jpeg",
        date: "19 mins ago",
        userId: 2,
        like: 32,
        comment: 9,
    },
    {
        id: 3,
        desc: "Good Morning",
        photo: "Assets/post/3.jpeg",
        date: "3 mins ago",
        userId: 3,
        like: 9,
        comment: 2,
    },
     {
        id: 4,
        desc: "Love!",
        photo: "Assets/post/4.jpeg",
        date: "50 mins ago",
        userId: 4,
        like: 39,
        comment: 19,
    },
    {
        id: 5,
        desc: "Hello :)",
        photo: "Assets/post/5.jpeg",
        date: "2 mins ago",
        userId: 5,
        like: 4,
        comment: 0,
    },
    {
        id: 6,
        desc: "Sunset",
        photo: "Assets/post/6.jpeg",
        date: "5 mins ago",
        userId: 6,
        like: 32,
        comment: 9,
    },
    {
        id: 7,
        desc: "Love for all,hatred for none",
        photo: "Assets/post/7.jpeg",
        date: "5 mins ago",
        userId: 7,
        like: 32,
        comment: 9,
    },
    {
        id: 8,
        desc: "Love for all,hatred for none",
        photo: "Assets/post/8.jpeg",
        date: "5 mins ago",
        userId: 8,
        like: 32,
        comment: 9,
    },
    {
        id: 9,
        desc: "Love for all,hatred for none",
        photo: "Assets/post/9.jpeg",
        date: "5 mins ago",
        userId: 9,
        like: 32,
        comment: 9,
    },
    {
        id: 10,
        desc: "Love for all,hatred for none",
        photo: "Assets/post/10.jpeg",
        date: "5 mins ago",
        userId: 10,
        like: 32,
        comment: 9,
    },
]